### ISSUE TITLE
Subscription not refreshed as it should

### ISSUE THREAD

**Issue by ndemoreau** [meteorhacks/subs-manager#13] opened 2014-07-14 16:08 UTC
I have these routes:

~~~coffee
Router.map ->
  @route "spaces",
    path: "/spaces"
    waitOn: ->
      subs.subscribe "allSpaces"

    data: ->
      spaces: Spaces.find()


  @route "buildingSpaces",
    path: "/buildings/:_id/spaces"
    waitOn: ->
      [Meteor.subscribe("buildingSpaces", @params._id),
       subs.subscribe "allBuildings"]

    data: ->
      building_id: @params._id
      building: Buildings.findOne(@params._id)
      spaces: Spaces.find()
      subTemplate:  "spacesList"
~~~

When I click the route "spaces", I get a list with all my spaces (let's say 10)

When I click the route "buildingSpaces", I should see all the spaces for a particular building.

This filter (by building) doesn't work with subscription manager. It shows all the 10 spaces instead. If I replace the subscription for the "spaces" route by Meteor.subscribe("allSpaces"), then it works correctly.

I guess that this is because all your subscriptions are cached using the name of the collection instead of using the name of the publication.

However, I still don't understand why I can't see my spaces filtered by building as this subscription is not using subs. It shouldn't used the cache subscription but it does. Any idea why?

Thank you!

**Comment by tomitrescak** [comment] 2015-01-14 01:02
Arunoda, I'm having the exact same problem, when records keep stacking up and therefore after while on the client I have ALL the data from the table. I guess this is not the problem, the problem is that the incorrect data is being used since I assume that at a given route only SUBSCRIBED data is available. I solved this by filtering on the route level as well. See below:

```javascript
Meteor.publish('schedule', function(id) {
  check(id, String);
  return Schedules.find({_id: id});
});

// route
Router.route('/practicals/:scheduleName/:scheduleId', {
  name: 'practicals',
  template: 'Practicals',
  waitOn: function () {
    return [
      subscriptions.subscribe('schedule', this.params.scheduleId)
    ];
  },
  data: function() {
    // I have to filter here, because if I browse several schedules ALL of the are cached on client
    return {
      schedule: Schedules.findOne({_id: this.params.scheduleId}, {reactive: false});
    }
  }
});
```

**Comment by arunoda** [comment] 2015-01-16 08:33
@tomitrescak that's the default behavior of this.
I think we discuss over at #26

**Comment by arunoda** [comment] 2015-01-16 08:34
@ndemoreau Yes. you've to do that.
This is how subs manager works.
Closing this issue.

**Closed by arunoda** 2015-01-16 08:34 UTC
